version: '3.1'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_ROOT: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - sql-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: "db"
      PMA_USER: root
      PMA_PASSWORD: 11111111
      UPLOAD_LIMIT: 300M
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - sql-network

volumes:
  my-db:


networks:
  sql-network:
