version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:1.13.0
    container_name: redisinsight
    ports:
      - "8001:8001"
    volumes:
      - redisinsight:/db
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  redisinsight: